apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - martin-deployment.yaml
  - postgis-statefulset.yaml
  - postgis-service.yaml
  - postgis-secret.yaml
  - bkup-config.yaml
