apiVersion: v1
kind: Namespace
metadata:
  name: argocd-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: argocd-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: argocd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    customer: vishanti
    ou: default-ou
    project: default-project
    region: SFO
    scloud: Mycloud
    zone: sfo-az1
    sku: tiny
    workload: pod
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo
          args:
            - "-text=hello world"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: argocd-test
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: argocd-test
spec:
  selector:
    app: backend
  ports:
    - port: 5678
      targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: unused-service
  namespace: argocd-test
spec:
  selector:
    app: does-not-exist
  ports:
    - port: 9999
      targetPort: 9999

